// <auto-generated />
using ASPCollegeBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPCollegeBooking.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20180429212604_OrgUpdate")]
    partial class OrgUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ASPCollegeBooking.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Days");

                    b.Property<DateTime>("End");

                    b.Property<string>("EventColor");

                    b.Property<bool>("IsFullDay");

                    b.Property<string>("Organizer");

                    b.Property<string>("ResourceId");

                    b.Property<int?>("RoomID");

                    b.Property<DateTime>("Start");

                    b.Property<string>("Title");

                    b.Property<int>("Weeks");

                    b.HasKey("Id");

                    b.HasIndex("RoomID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ASPCollegeBooking.Models.Rooms", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EventColor");

                    b.Property<bool>("IsBookable");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ASPCollegeBooking.Models.Events", b =>
                {
                    b.HasOne("ASPCollegeBooking.Models.Rooms", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");
                });
#pragma warning restore 612, 618
        }
    }
}
